SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `DBEMPLOYEES` ;
CREATE SCHEMA IF NOT EXISTS `DBEMPLOYEES` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DBEMPLOYEES` ;

-- -----------------------------------------------------
-- Table `DBEMPLOYEES`.`EMPLOYEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBEMPLOYEES`.`EMPLOYEE` ;

CREATE  TABLE IF NOT EXISTS `DBEMPLOYEES`.`EMPLOYEE` (
  `ID` VARCHAR(5) NOT NULL ,
  `NAME` VARCHAR(100) NOT NULL ,
  `SALARY` DEC(15,2) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
